project:
  type: website

website:
  title: "mldurga"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mldurga
      - icon: twitter
        href: https://twitter.com/durgaamma2005
format:
  html:
    theme: cosmo
    css: styles.css



